# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - healthygultlog-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Use Pre-installed .NET Core
        run: dotnet --version # Verify pre-installed .NET version

      - name: Use Pre-installed Node.js
        run: node --version # Verify pre-installed Node.js version

      - name: Install Angular CLI (if not already installed)
        run: |
          if (!(ng version > $null 2>&1)) {
            npm install -g @angular/cli
          }

      - name: Install dependencies
        run: npm install
        working-directory: ./fodmaplog.client

      - name: Build Angular app
        run: ng build --configuration production
        working-directory: ./fodmaplog.client

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
          
      - name: Upload Angular build artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: ./fodmaplog.client/dist/fodmaplog.client

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'healthygultlog-app'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3DB2C653394541C595F4B640CF3FF3E8 }}

  deploy-client:
    runs-on: ubuntu-latest # Use Linux runner for deployment
    needs: build
    
    steps:
      - name: Download artifact from artifact for deployment job
        uses: actions/download-artifact@v4
        with:
          name: angular-app
      
      - name: Deploy Client to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'healthygutlog-client'
          slot-name: 'Production'
          package: ./fodmaplog.client/dist/fodmaplog.client
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CLIENT }}
